apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocket:manager
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.rocket.io
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.rocket.io
  resources:
  - managedclusters/finalizers
  - managedclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.rocket.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspace.rocket.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspace.rocket.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.rocket.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.rocket.io
  resources:
  - applications/finalizers
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kruise.io
  resources:
  - clonesets
  - statefulset
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocket:manager:metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocket:manager:proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rocket:agent
rules:
- apiGroups:
  - storage.rocket.io
  resources:
  - managedclusters
  verbs:
  - get
  - update
  - watch
  - list
- apiGroups:
  - storage.rocket.io
  resources:
  - managedclusters/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps.rocket.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.rocket.io
  resources:
  - applications/status
  verbs:
  - get
  - update
  - patch