---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.rocket.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.rocket.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - apps.rocket.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.rocket.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.rocket.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.rocket.io
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.rocket.io
  resources:
  - managedclusters/status
  verbs:
  - get
  - patch
  - update
